name: CI
on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: mskelton/setup-yarn@v1
        with:
          version: 1.22.4
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: "yarn"

      - run: yarn --frozen-lockfile
      - run: yarn lint && yarn build
